// <auto-generated />
using System;
using BarWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarWebApplication.Migrations
{
    [DbContext(typeof(WebAppContext))]
    partial class WebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarWebApplication.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CategoryID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BarWebApplication.Models.DailyDeal", b =>
                {
                    b.Property<int>("DailyDealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DailyDealID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DailyDealDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DailyDealDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte[]>("DailyDealImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DailyDealName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("DailyDealPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("DailyDealQuantity")
                        .HasColumnType("int");

                    b.HasKey("DailyDealId")
                        .HasName("PK__DailyDea__2E1B31B29C667241");

                    b.ToTable("DailyDeal");
                });

            modelBuilder.Entity("BarWebApplication.Models.DailyDealOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("CurrentStatus")
                        .HasColumnType("bit");

                    b.Property<int>("DailyDeal")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderMessage")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("OrderType")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("DailyDeal");

                    b.HasIndex("OrderType");

                    b.ToTable("DailyDealOrder");
                });

            modelBuilder.Entity("BarWebApplication.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ItemId");

                    b.HasIndex("Category");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("BarWebApplication.Models.ItemOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("CurrentStatus")
                        .HasColumnType("bit");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderMessage")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("OrderType")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__ItemOrde__C3905BAF9BDD4A3C");

                    b.HasIndex("Item");

                    b.HasIndex("OrderType");

                    b.ToTable("ItemOrder");
                });

            modelBuilder.Entity("BarWebApplication.Models.OrderType", b =>
                {
                    b.Property<bool>("TypeId")
                        .HasColumnName("TypeID")
                        .HasColumnType("bit");

                    b.Property<string>("OrderType1")
                        .IsRequired()
                        .HasColumnName("OrderType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TypeId")
                        .HasName("PK__OrderTyp__516F0395FC748589");

                    b.ToTable("OrderType");
                });

            modelBuilder.Entity("BarWebApplication.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ReservationID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PeopleNo")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("BarWebApplication.Models.DailyDealOrder", b =>
                {
                    b.HasOne("BarWebApplication.Models.DailyDeal", "DailyDealNavigation")
                        .WithMany("DailyDealOrder")
                        .HasForeignKey("DailyDeal")
                        .IsRequired();

                    b.HasOne("BarWebApplication.Models.OrderType", "OrderTypeNavigation")
                        .WithMany("DailyDealOrder")
                        .HasForeignKey("OrderType")
                        .IsRequired();
                });

            modelBuilder.Entity("BarWebApplication.Models.Item", b =>
                {
                    b.HasOne("BarWebApplication.Models.Category", "CategoryNavigation")
                        .WithMany("Item")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK__Item__Category__398D8EEE")
                        .IsRequired();
                });

            modelBuilder.Entity("BarWebApplication.Models.ItemOrder", b =>
                {
                    b.HasOne("BarWebApplication.Models.Item", "ItemNavigation")
                        .WithMany("ItemOrder")
                        .HasForeignKey("Item")
                        .HasConstraintName("FK__ItemOrder__Item__3E52440B")
                        .IsRequired();

                    b.HasOne("BarWebApplication.Models.OrderType", "OrderTypeNavigation")
                        .WithMany("ItemOrder")
                        .HasForeignKey("OrderType")
                        .HasConstraintName("FK__ItemOrder__Order__3F466844")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
